### ISSUE TITLE
Upgrade Javalin from 5 to 6

### ISSUE THREAD

**Issue by kklamberty** [UMM-CSci-3601/3601-iteration-template#1406]
I'm not sure when version 6 will be officially released, but it sounds like some challenges we may have faced using flat files could be alleviated (though I'm not sure we faced those particular challenges). The 4th beta is around and Javalin folks are looking for feedback for any final tweaks before the release of 6.0.0

https://javalin.io/migration-guide-javalin-5-to-6

See #1564

**Comment by NicMcPhee** [comment]
v6 has now been out for over a year now, and Dependabot keeps creating PRs to upgrade from v5 to v6 (e.g., #1564). None of those compile, though, because we will have to update our code to work with v6. I'm working on making the necessary changes as addition commits on #1564, and hopefully will have that done for this semester.
