### ISSUE TITLE
Clean up the regexes in add-user.component.ts

### ISSUE THREAD

**Issue by helloworld12321** [UMM-CSci-3601/3601-iteration-template#313]
cf. UMM-CSci-3601/3601-lab4-mongo#35.

Some of the regexes are a bit redundant (`^[0-9]+[0-9]?` for an age) and some of them are pretty weird. (`^[A-Za-z0-9\\s]+[A-Za-z0-9\\s]+$(\\.0-9+)?` for a human name). 🙃

Building off of @NicMcPhee's suggestions, I'd recommend

1. simplifying the age regex,
2. removing the user name regex (or, if you'd like, replacing it with something more unicode-friendly), and
3. adding a simple regex for email addresses.

(Maybe something like `[^@]+@[^@]+` for the email regex? I'd rather be overly permissive here than overly restrictive—we wouldn't want to accidentally forbid [plus extensions][], for example.)

[plus extensions]: https://helpspot.pobox.com/index.php?pg=kb.page&id=58

**Comment by helloworld12321** [comment]
Actually, given that Angular provides a built-in Validator for matching email addresses, so let's use that instead. In that case, the only two changes I'd like to make are

1. simplifying the age regex, and
2. removing the name regex. 🙂

**Comment by floogulinc** [comment]
We still have to validate the email on the server side right?

**Comment by helloworld12321** [comment]
Oh, good catch! Yes, on the server, we're verifying emails against this regex: `^[a-zA-Z0-9_!#$%&'*+/=?`{|}~^.-]+@[a-zA-Z0-9.-]+$`

which seems decent. 🤷🏻‍♂️

Do you think it's an issue that we aren't using the exact same validation logic on both the server-side and the client-side?

**Comment by floogulinc** [comment]
So long as the client is stricter than the server it should be OK. All we really _need_ is for the server to sanitize the input enough for it to be safe for database operations but in a more real use case we would want to make sure email addresses are valid if we are actually sending out emails. There really is no _perfect_ regex for email address, they are very complicated (https://stackoverflow.com/questions/201323/how-to-validate-an-email-address-using-a-regular-expression). The real solution is probably to use a third-party email address validation library rather than a regex. Apache Commons has a nice validators package: http://commons.apache.org/proper/commons-validator/apidocs/org/apache/commons/validator/package-summary.html
It includes an [email validator](http://commons.apache.org/proper/commons-validator/apidocs/org/apache/commons/validator/EmailValidator.html) as well as some other potentially useful validators for things like URLs and dates.
