### ISSUE TITLE
Ignore package-lock.json at root

### ISSUE THREAD

**Issue by floogulinc** [UMM-CSci-3601/3601-iteration-template#36]
Some groups have a `package-lock.json` in the root directory of their repos. This likely happens from running some `npm` command in `/` rather than `/client` so we should just gitignore `package-lock.json` in [`/.gitignore`](https://github.com/UMM-CSci-3601/3601-iteration-template/blob/master/.gitignore).

**Comment by NicMcPhee** [comment]
Is there a way we could "prevent" folks from making that mistake in the first place? I feel that when it happens it's often because of some confusion, and then creates additional confusion. If we could have some sort of error or warning happen when they initially do The Wrong Thing, then we might address that confusion earlier and in a more useful way.

I don't really know what that might look like, though. Have a `package.json` file that is deliberately ill-formed, perhaps containing a message that tells them they shouldn't be running `nom` commands in this directory?
