### ISSUE TITLE
Cypress intermittently fails because of detached elements in the DOM

### ISSUE THREAD

**Issue by helloworld12321** [UMM-CSci-3601/3601-iteration-template#649]
I haven't looked into how to fix this issue—we may need to adjust our retry logic? 🤷🏻‍♂️

[Here](https://drive.google.com/file/d/1Cf8COuoPOCdm4OPkB8fljIcs031uvoRw/view?usp=drivesdk) are logs from a failing run. The relevant section is this:

```
2022-01-23T23:49:24.6126996Z [31m  1 failing[0m
2022-01-23T23:49:24.6127177Z 
2022-01-23T23:49:24.6127500Z [0m  1) User list
2022-01-23T23:49:24.6127979Z        Should type something in the age filter and check that it returned correct elements:
2022-01-23T23:49:24.6128931Z [0m[31m     CypressError: Timed out retrying after 4000ms: `cy.should()` failed because this element is detached from the DOM.
2022-01-23T23:49:24.6129248Z 
2022-01-23T23:49:24.6130007Z `<mat-card-title _ngcontent-pqi-c75="" class="mat-card-title user-card-name">Bolton ...</mat-card-title>`
2022-01-23T23:49:24.6130357Z 
2022-01-23T23:49:24.6130818Z Cypress requires elements be attached in the DOM to interact with them.
2022-01-23T23:49:24.6131073Z 
2022-01-23T23:49:24.6131772Z The previous command that ran was:
2022-01-23T23:49:24.6131979Z 
2022-01-23T23:49:24.6132227Z   > `cy.get()`
2022-01-23T23:49:24.6132387Z 
2022-01-23T23:49:24.6132898Z This DOM element likely became detached somewhere between the previous and current command.
2022-01-23T23:49:24.6133197Z 
2022-01-23T23:49:24.6133539Z Common situations why this happens:
2022-01-23T23:49:24.6134058Z   - Your JS framework re-rendered asynchronously
2022-01-23T23:49:24.6134647Z   - Your app code reacted to an event firing and removed the element
2022-01-23T23:49:24.6134899Z 
2022-01-23T23:49:24.6135596Z You typically need to re-query for the element or add 'guards' which delay Cypress from running new commands.
2022-01-23T23:49:24.6135907Z 
2022-01-23T23:49:24.6136460Z https://on.cypress.io/element-has-detached-from-dom[0m[90m
```

(Apologies for the ANSI escape noise. For best viewing, run `less -R <logfile>`.)

**Comment by NicMcPhee** [comment]
@helloworld12321 I've had this happen sporadically to me as well. Did you ever figure out what the issue was or how to fix it? When it's happened to me I've always had it succeed on a re-run, so it always smelled like a caching/timing problem.

**Comment by helloworld12321** [comment]
Unfortunately not, sorry :(

I agree that it looks like a timing problem, though.

**Comment by NicMcPhee** [comment]
You're also using a Mac, right? I wonder if this ever happens in the lab. I don't think I've seen it in GitHub Actions.

**Comment by helloworld12321** [comment]
I've definitely seen this in GitHub actions—maybe not recently, though.

**Comment by NicMcPhee** [comment]
I think I may have figured out the problem here. The Cypress error actually includes a link to [this collection of info on error messages](https://docs.cypress.io/guides/references/error-messages#cy-failed-because-the-element-you-are-chaining-off-of-has-become-detached-or-removed-from-the-dom), which in turn links to [this blog post specifically about the "detached elements in the DOM" problem](https://www.cypress.io/blog/2020/07/22/do-not-get-too-detached/).

One source of this problem (which I'm guessing is _our_ source) is that you can put in search terms and start doing things like looping over the list before the list has fully loaded. If it changes/updates while you're looping through it, you will get these "detached elements" errors. The fix is to add an assertion that "forces" the list to have fully loaded, and _then_ do the looping over the items in the list.

I'm going to try adding this to our code and see if that seems to make the tests pass more reliably. Because it's quite sporadic, we might not really know until the next big dump of Dependabot PRs, which do a nice job of highlighting race conditions in our tests. :stuck_out_tongue_winking_eye:

**Comment by NicMcPhee** [comment]
Actually, student experiments with this idea aren't winning the big prizes. I think the problem is that there are actions that don't fully 'resolve' until the component calls the service which sends an HTTP request to the server which queries the DB and then all of that returns something which eventually causes the appropriate data to be rendered. There's no simple way in the Cypress tests to "wait" or "force" that to be done before continuing.

[This post](https://github.com/cypress-io/cypress/issues/7306#issuecomment-641965688) (on a _very_ long thread related to this problem) suggests that we can use the Angular `angular.getTestability('body').whenStable(...)` to check that a part of the Angular is stable. I don't know, though, that this will help; if the delay to/from the server is long enough then it might _seem_ stable just because it hasn't gotten a response back and started re-rendering.

I want to look at [this video](https://glebbahmutov.com/blog/detached/) which is all about this issue and _might_ be useful?

Unfortunately everything I've seen doesn't seem to address the need to potentially wait for a response from a (slow) server, and I'm not 100% sure that's even possible. How could you tell that the server wasn't going to respond "any second now"?

**Comment by floogulinc** [comment]
I'm still planning to look into this when I have time. I want to see if there is a way to replicate Protractor's ability to wait for Angular async stuff.

**Comment by NicMcPhee** [comment]
In reading through some of [the introductory Cypress documentation](https://docs.cypress.io/guides/getting-started/writing-your-first-test#Step-4-Make-an-assertion) (see the "Page transitions" section), I wonder if there's something we could do with either (a) fiddling the delays in the Cypress config or (b) altering our code so that Cypress "realizes" that the pages aren't yet fully loaded?

**Comment by kklamberty** [comment]
As Nic pointed out, the linked blog post [specifically about the "detached elements in the DOM" problem](https://www.cypress.io/blog/2020/07/22/do-not-get-too-detached/) explains some things to try. One thing I noticed we do have is some fragile chaining where we try to continue after clicking on something, but click is not safe to chain off of. Also, some of the fixes that I noticed do things like wait until there are more than 0 elements... if you know there will be 2, you should probably just say 2. cy.get waits until the state you are waiting for exists (or until it times out), so putting exactly what you're waiting for in there makes sense.
